---
ansible_host: 100.61.0.103
nickname: watsrx01
# 
## Firewall Interface Details ##
interfaces:
  - name: fe-0/0/7.0
    description: Outside - Vocus VIE123456
    address: 192.168.1.107
    mask_long: 255.255.255.0
    mask_short: 24
    zone: outside

  - name: fe-0/0/6.0
    description: DMZ
    address: 10.168.1.107
    mask_long: 255.255.255.0
    mask_short: 24
    zone: dmz
