---
- name: "Copy Module - Push a file from host to target - watrpi01/02/03"
  hosts: linuxs
  gather_facts: no
  connection: local
  become: yes
  tasks:
   - name: "=== Play:1 - Copy ~/file1.txt to pi ==="
     copy:
       src: file1.txt
       dest: /home/sysadmin-jb/file1.txt