---
- name: S5E1 IOS Facts Examples
  hosts: cpes
  tasks:
  - name: "== S5E1 Task 1: Get IOS facts store output to local register cli_result =="
    register: cli_result
    ios_facts:
      gather_subset: 
        - min
        - '!default'
        - '!hardware'
      gather_network_resources: interfaces

  - name: "== S5E1 Task 2: Copy contents of CLI result to local file through nice JSON filter =="
    copy:
      content: "{{ cli_result | to_nice_json }}"
      dest: "outputs/{{ inventory_hostname}}_S5E1_outputs.json"

